services:
  mysql:
    image: mysql:8.4
    container_name: amm-approval-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: amm_approval
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
