export const errorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  REQUEST_ALREADY_COMPLETED: "REQUEST_ALREADY_COMPLETED",
  REQUEST_ALREADY_REJECTED: "REQUEST_ALREADY_REJECTED",
  APPROVER_NOT_FOUND: "APPROVER_NOT_FOUND",
  APPROVAL_TOKEN_INVALID: "APPROVAL_TOKEN_INVALID",
  APPROVAL_ALREADY_PROCESSED: "APPROVAL_ALREADY_PROCESSED",
  OTP_INVALID_OR_EXPIRED: "OTP_INVALID_OR_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",
  OTP_NOT_VERIFIED: "OTP_NOT_VERIFIED",
  PDF_NOT_AVAILABLE: "PDF_NOT_AVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCode = keyof typeof errorCodes;
